CC=gcc
compile:
	$(CC) -DLOCALEXEC -Wall -o lab5b.x lab5b.c
run:
	./lab5b.x
run_tests:
	./lab5b.x < ./tests/test1.in
	./lab5b.x < ./tests/test2.in
	./lab5b.x < ./tests/test3.in
	./lab5b.x < ./tests/test4.in
	./lab5b.x < ./tests/test5.in
