CC=gcc
compile:
	$(CC) -DLOCALEXEC -o lab5a.x lab5a.c
run:
	./lab5a.x
run_tests:
	./lab5a.x < ./tests/in1.txt
	./lab5a.x < ./tests/in2.txt
	./lab5a.x < ./tests/in3.txt
	./lab5a.x < ./tests/in4.txt
make clean:
	rm -f *.o *.x *.as
